version: "3"
services:
  app:
    container_name: gql_app
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app/graphqlApp
    depends_on:
      - mongo
    networks:
      - gql_net
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - gql_net

networks:
  gql_net:
    driver: bridge
